### PR TITLE
Fix/complete Italian translations

### PR DESCRIPTION
**Pull request by mlocati**

### CODE REVIEW

**Comment by AnnaTomanek** [comment]
Hi Michele, thanks a lot for your contribution! Your pull request has just been merged and your changes will be available in the next release.

A minor note, though: I needed to correct some placeholders (escaped `\"%1\"`) and punctuation marks since you added characters such as `“”’…`. Please don't replace these in the future - thanks in advance!

As promised, we have a free CKFinder 3 license for anyone that provides a significant translation update. If you ever need such a license, just [contact us](http://cksource.com/contact) and send the URL that your CKFinder installation will be used at and we'll provide you the license key.

Thanks again for your help, it is much appreciated both by development team and CKFinder users!

**Comment by mlocati** [comment]
Hi @AnnaTomanek!

> A minor note, though: I needed to correct some placeholders (escaped \"%1\") and punctuation marks since you added characters such as “”’…. Please don't replace these in the future - thanks in advance!

Any reason for that? I usually use characters like `“`, `”` and `’` in translations because they are valid punctuation marks (at least for Italian - see for instance the box on the right at http://it.wikipedia.org/wiki/Punteggiatura).
Even more important, they can be safely used un-escaped in JavaScript and in HTML, without any need to escape them.
Furthermore, like the much used (in Italian) `è` character, they are widely supported in UTF-8.

**Comment by wwalc** [comment]
Thanks again for the contribution! 

Let me explain why @AnnaTomanek asked you to not change the punctuation marks. When developing the software one of the most important things is to be consistent. This is why we are very strict about using the correct code style in source code. This attitude affects all other things around the project, including language files. 
While being sometimes painful, it quickly pays off. For example, imagine a situation where multiple translators working on the same language file have different preferences. What we should do then, allow for unnecessary diffs whenever person A updates a file previously translated by person B?
The other scenario where this attitude turns out to be useful is when we replace certain strings in multiple files at once (e.g. we replaced placeholders quite recently). If there are no rules it makes such tasks more error prone and time consuming.

I hope its more clear now. Thank you for your understanding.

**Comment by mlocati** [comment]
I agree. Thanks for the explanation

**Comment by AnnaTomanek** [comment]
Hi Michele,

Hope you are fine, and thanks again for helping out with CKFinder 3 localization.

We are nearing the release of CKFinder 3.1 and there are some new language strings that need translating. Would you be so kind as to look at them and help when you have a moment to spare? This would be much appreciated!

The latest language files were uploaded to this repository (https://github.com/ckfinder/ckfinder-translations).

Here are the latest development samples that show what CKFinder 3.1 will look like: https://cksource.com/temp/ckfinder310dev/samples/index.html

We are planning to release CKFinder 3.1 next Tuesday (**October 27, 2015**).

Thanks again for your contribution and do not hesitate to contact us should you have any questions or comments!

**Comment by mlocati** [comment]
Hi Anna!

Done: see https://github.com/ckfinder/ckfinder-translations/pull/41

All the best,
Michele

PS: If I recall correctly, you give a a free license of CKFinder to the
translators. Is it right? In this case, could you grant me a license of it?
Thank you!

2015-10-22 9:09 GMT+02:00 Anna Tomanek notifications@github.com:

**Pull request merged**
