### PR TITLE
Minor Italian fixes

### PR DESCRIPTION
**Pull request by mlocati**

### CODE REVIEW

**Comment by AnnaTomanek** [comment]
Thanks, Michele! By the way, you can start watching the repository (just click the "Watch" button above). I'll be creating Issues (like #52) before releases, whenever there are new language strings to be translated - by watching the repository you will be automatically notified about this.

Thanks again for your help!

**Comment by mlocati** [comment]
> Thanks, Michele! By the way, you can start watching the repository (just click the "Watch" button above).

@AnnaTomanek I did that, but I keep getting messages about languages I'm not interested in. What about adding a new issue just for that? So, translators would just subscribe to that issue and receive notifications only when needed...

**Comment by AnnaTomanek** [comment]
Sorry about that - I created issue #57 for this. I will not be closing it, I'll be updating it when help is needed. Thank you!

**Comment by mlocati** [comment]
Thanks, Anna!

**Pull request merged**
