### PR TITLE
Translated To Arabic  by Essam Ambr.

### PR DESCRIPTION
**Pull request by JaMaYcKa2B1**

### CODE REVIEW

**Comment by zaak** [comment]
Thank you @JaMaYcKa2B1! Please note that you have to sign the CLA before we can merge this PR - you should receive an appropriate email message.

**Comment by JaMaYcKa2B1** [comment]
> 



> Thank you @JaMaYcKa2B1! Please note that you have to sign the CLA before we can merge this PR - you should receive an appropriate email message.

Hi PRO
how  to sign the CLA and what is the next procedure?
can you help me

**Comment by zaak** [comment]
@JaMaYcKa2B1: Please check your email archive. You should have received an email message with a link to sign the CLA.

**Comment by JaMaYcKa2B1** [comment]
> @JaMaYcKa2B1: Please check your email archive. You should have received an email message with a link to sign the CLA.

Hi
Dear friends,

I have checked my emails and these are your messages, and there are no message with a link to sign the CLA
 Please check your email .

**Comment by JaMaYcKa2B1** [comment]
*HiDear friends, I have checked my emails and these are your messages, and
there are no message with a link to sign the CLA*

* Regards, *
* Essam Ambr *



[image: Essam Ambr (elsaaveryn2b) – Crowdin]
<https://crowdin.com/profile/elsaaveryn2b>  [image: Essam Ambr (JaMaYcKa) -
Transifex] <https://www.transifex.com/user/profile/elsaaveryn2b/>  [image:
JaMaYcKa2B1 (Essam Ambr) - GitHub] <https://github.com/JaMaYcKa2B1>



.

‫في الأربعاء، 27 يوليو 2022 في 1:40 م تمت كتابة ما يلي بواسطة ‪Paweł
Wiaderny‬‏ ***@***.***‬‏>:‬

**Comment by JaMaYcKa2B1** [comment]
> @JaMaYcKa2B1: Please check your email archive. You should have received an email message with a link to sign the CLA.


Thank you  @zaak  
But i think   if the message I received in The date is July 27 was transferred to the spam folder
 And since it's since , it may have been emptied automatically because it is now clean and I can't find any messages in this folder, 
neither new nor old

**Comment by JaMaYcKa2B1** [comment]
**no problem my friend @zaak 
anyway
You know what I'm thinking now


All this headache
What for
It is a free contribution
With great effort and fatigue
And in return for all that
Just the biggest headache of bureaucratic procedures

So my best solution is to delete it completely and close this post
Thanx alot**

**Comment by zaak** [comment]
@JaMaYcKa2B1: It would be a shame to waste your work like that. Please give me a minute, we'll figure something out 🙂

**Comment by zaak** [comment]
@JaMaYcKa2B1: Thank you for your contribution. The Arabic translation you provided will be published in the upcoming release.

As promised, we have a free CKFinder 3 license for anyone that provides a significant translation update or a new localization. If you ever need such a license, just [contact us](http://cksource.com/contact) and send the URL that your CKFinder installation will be used and we'll provide you the license key.

Thanks again for your work!

**Comment by JaMaYcKa2B1** [comment]
> 
Dear @zaak  
I hope that all is well with you.
First of all
Thank you very much for your interest in the topic and for taking that into consideration to help us 

Thank you for your a professional and wonderful message from you
It expresses your commitment and professionalism in dealing with situations


SO in short people like you
They are the ones who make the difference in any organization that has a professional work environment

 Yours sincerely,
Essam Ambr

**Pull request merged**
