### PR TITLE
Added missing Bosnian translations

### PR DESCRIPTION
**Pull request by axterbach**
I added translation strings for: folders.newSubfolder, upload.progressMessage, settings.viewTypeCompact, errors.deleteFilePermissions & errors.renameFilePermissions.

### CODE REVIEW

**Comment by AnnaTomanek** [comment]
Hi @axterbach, thanks a lot for your contribution! In order for us to use it, we would like to ask you to please sign the CLA (Contributor License Agreement). Unfortunately, we are unable to incorporate your translations without this. Thank you very much for your understanding!

**Comment by vokiel** [comment]
@axterbach we noticed you're using masked email here on GitHub. Please contact us on https://ckeditor.com/contact with your personal email so we can send you an electronic CLA sign request.

**Comment by axterbach** [comment]
@vokiel Done. I'm waiting for your response.
Btw, my email is visible on my GitHub profile now.
Thank you.

**Comment by vokiel** [comment]
> Btw, my email is visible on my GitHub profile now.

@axterbach you don't have to expose your email in your profile, or in commits. You can have it masked, we just needed it to send you the CLA sign request to.

**Comment by axterbach** [comment]
@vokiel I'm sorry for delay. All done.
Thank you very much for your assistance.

**Comment by AnnaTomanek** [comment]
Hi @axterbach ,

I'm terribly sorry that I somehow missed you signing the CLA :disappointed: . Sorry for the delay!

The updated Bosnian translation isa now merged, it will be published in the upcoming release of CKFinder. Thanks again for your help, it's much appreciated!

**Comment by axterbach** [comment]
@AnnaTomanek It can never be too late. :smile: I'm using CKFinder for some of my own projects. And to spend couple hours working on translation was a fair trade.
So, thank you and keep up a good work.

**Pull request merged**
