### PR TITLE
translate some phrases into Farsi

### PR DESCRIPTION
**Pull request by hamid914**

### CODE REVIEW

**Comment by AnnaTomanek** [comment]
Hi Hamid, thank you so much for your contribution. Could you, however, sign the [Contributor License Agreement](http://cla.ckeditor.com/check/ckfinder/ckfinder-translations/72) first? We cannot accept your code without it. Thank you!

**Comment by hamid914** [comment]
Hi Anna, sorry for my late reply. I signed the agreement.
Where should I submit the signed agreement file now?

**Comment by vokiel** [comment]
@hamid914 you should get an e-mail from eSignLive (secure e-signature solution provider we use for signing the CLA). There should be a link to the CLA signing form, which after filling in will automatically set the status for the PR and let all of us know about the signing being done.

**Comment by hamid914** [comment]
@vokiel Thanks for your reply, but I didn't receive any email from eSignLive. I searched my inbox but no result found.

**Comment by vokiel** [comment]
@hamid914 this is because you're probably using _Keep my email address private_ GitHub option at your account. Because of that we couldn't send you the CLA request.
Please contact us on https://cksource.com/contact so I can create one manually.

**Comment by hamid914** [comment]
@vokiel Thanks for your reply.
I submitted the contact form and signed up on the website.

**Comment by AnnaTomanek** [comment]
Thank you so much, Hamid! Your changes will be available in the next CKFinder release.

By the way, would you like to help us complete the Persian localization of CKEditor? CKEditor 4 is missing some strings, and the new CKEditor 5 is completely empty: https://www.transifex.com/ckeditor/ckeditor5/language/fa/

If you'd be interested (and that would be much appreciated!), just join us at [Transifex](https://www.transifex.com/ckeditor/). Thanks in advance!

**Pull request merged**
