### PR TITLE
Hungarian translations

### PR DESCRIPTION
**Pull request by Carmachy**

### CODE REVIEW

**Comment by AnnaTomanek** [comment]
Hi,

thank you very much for your contribution!

There are just a few strings left untranslated now, any chance you could do these, too?

```
"MoveManyFilesWait": "Moving %1 files. Kérem várjon.",
"CopyManyFilesWait": "Copying %1 files. Kérem várjon.",
// Chooses a resized image.
"ChooseResizedImage": "Choose Resized",
// Custom image size.
"Custom": "Custom",
"GettingFileData": "Getting file data. Please wait.",
// This reads, for example: Files uploaded: 5 of 12
"UploadFilesCountProgress": "{filesUploaded} of {filesTotal}",
"UploadBytesCountProgress": "({bytesUploaded} of {bytesTotal})",
"13": "The connector configuration file is invalid.",
"14": "Invalid connector plugin: %1.",
```

By the way, if you were willing to add translations for the Image Edit presets, you can find samples of what they do on the CamanJS [Interactive Examples](http://camanjs.com/examples/) page.

Thanks again for your help with this!

**Comment by Carmachy** [comment]
Hi!

I translated the missing strings.

Carmachy

**Comment by AnnaTomanek** [comment]
Thanks so much!

Seems I missed one more :/

```
"FileUploaded": "File uploaded",
```

It would be great if you could add it, too, and sorry about any inconvenience caused!

**Comment by AnnaTomanek** [comment]
Hi Carmachy, thanks a lot for your help! Your pull request has just been merged and your changes will be available in the next CKFinder release. 

As promised, we have a free CKFinder 3 license for anyone that provides a significant translation update. If you ever need such a license, just [contact us](http://cksource.com/contact) and send the URL that your CKFinder installation will be used at and we'll provide you the license key.

Thanks again for your help, it is much appreciated both by development team and CKFinder users!

**Comment by AnnaTomanek** [comment]
Hi Carmachy,

Hope you are fine, and thanks again for helping out with CKFinder 3 localization.

We are nearing the release of CKFinder 3.1 and there are some new language strings that need translating. Would you be so kind as to look at them and help when you have a moment to spare? This would be much appreciated!

The latest language files were uploaded to this repository (https://github.com/ckfinder/ckfinder-translations).

Here are the latest development samples that show what CKFinder 3.1 will look like: https://cksource.com/temp/ckfinder310dev/samples/index.html

We are planning to release CKFinder 3.1 next Tuesday (**October 27, 2015**).

Thanks again for your contribution and do not hesitate to contact us should you have any questions or comments!

**Comment by AnnaTomanek** [comment]
Hi Carmachy,

we are slowly nearing the CKFinder 3.3 release (and the beta release of the new ASP.NET connector!). Could I ask you to have a look at the translations and provide the missing ones?

The latest development snapshot was uploaded to: https://cksource.com/temp/ckfinder330dev/ckfinder.html - you can use it to check where the language strings are used.

Thanks in advance - your help is much appreciated!

**Pull request merged**
