### PR TITLE
Update zh-cn.json

### PR DESCRIPTION
**Pull request by Jayin**

### CODE REVIEW

**Comment by AnnaTomanek** [comment]
Hi Jayin, thanks again for your help!

Two minor things/questions:

[Line 98](https://github.com/Jayin/ckfinder-translations/blob/major/lang/zh-cn.json#L98) - translation for "of" missing, I'm not sure the Chinese version makes sense now (it should read like: "5 of 10").

```
"filesCountProgress": "{filesTotal}{filesUploaded}",
```

[Line 153](https://github.com/Jayin/ckfinder-translations/blob/major/lang/zh-cn.json#L153) - translation missing:

```
"fileNameNotEmpty": "[MISSING]The file name cannot be empty.",
```

Thanks in advance for looking into this!

**Comment by Jayin** [comment]
Updated

**Comment by AnnaTomanek** [comment]
Hi Jayin, thanks a lot for your contribution! Your pull request has just been merged and your changes will be available in the next release.

As promised, we have a free CKFinder 3 license for anyone that provides a significant translation update. If you ever need such a license, just [contact us](https://cksource.com/contact) and send the URL that your CKFinder installation will be used at and we'll provide you the license key.

Thanks again for your help, it is much appreciated both by development team and CKFinder users!

**Comment by Jayin** [comment]
Thanks🚀

**Pull request merged**
